# Generated by Django 3.2 on 2022-01-22 19:12

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'garbage_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GarbageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emoji', models.CharField(max_length=2)),
                ('language_code', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'garbage_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('utc_timestamp', models.DateTimeField(auto_now=True)),
                ('unix_timestamp', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bot', models.BooleanField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('language_code', models.CharField(blank=True, max_length=3, null=True)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('utc_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
